jquery_lang_js.prototype.lang.el = {
	'Home':'Αρχική',
	'About':'Σχετικα',
	'Portofolio':'Πορτοφολιο',
	'Prices':'Τιμες',
	'Contact':'Επικοινωνια',
	'About WebWizards':'Σχετικα Με Τους WebWizards',
	'Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla':'Βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα βλα',
	'Who Are We?':'Ποιοι Ειμαστε;',
	'Portfolio':'Δουλειες Μας',
	'Pricelist':'Κοστολογιο',
	'Prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices prices':'Τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές τιμές',
	'Contact':'Επικοινωνια',
	'Name<span>*</span>':'Όνομα<span>*</span>',
	'Email<span>*</span>':'Email<span>*</span>',
	'Message':'Μήνυμα',
	'Send':'Αποστολή',
	'Reset':'Εκκαθάριση',
	'<span>*</span> Required fields':'<span>*</span> Απαραίτητα πεδία',
}
