jquery_lang_js.prototype.lang.el = {
	'Home':'Αρχική',
	'About':'Σχετικα',
	'Portofolio':'Πορτοφολιο',
	'Prices':'Τιμες',
	'Contact':'Επικοινωνια',
	'About WebWizards':'Σχετικα Με Τους WebWizards',
	'Webwizards are a small and agile group of computer science students, that specialize in web development and in applying new and innovative technologies. Our purpose is to reinforce the web profile of your company through the usage of functional and appealing web pages and other web services, resulting in a transition to the digital age. Some of the technologies we specialize in are:':'Οι WebWizards είναι μία μικρή και ευέλικτη ομάδα φοιτητών πληροφορικής, που εξειδικεύονται στη κατασκευή ιστοσελίδων και την εφαρμογή νέων και καινοτόμων τεχνολογιών. Σκοπός μας είναι να ενισχύσουμε το διαδικτυακό προφίλ της εταιρίας σας, μέσα από τη χρήση λειτουργικών και όμορφων ιστοσελίδων και άλλων διαδικτυακών υπηρεσιών, με αποτέλεσμα τον εκσυγχρονισμό της εταιρίας σας και τη μετάβασή της στη ψηφιακή εποχή.   Ανάλογα με τις ανάγκες σας θα χρησιμοποιήσουμε και τις πιο κατάλληλες τεχνολογίες. Οι WebWizards εξειδικεύονται σε πληθώρα τεχνολογιών:',
	'Who Are We?':'Ποιοι Είμαστε;',
	'Portfolio':'Προηγούμενες Δουλειές Μας',
	'Pricelist':'Κοστολόγιο',
	'Contact':'Επικοινωνια',
	'Name <span class="req">*</span>':'Όνομα <span class="req">*</span>',
	'Email <span class="req">*</span>':'Email <span class="req">*</span>',
	'Message':'Μήνυμα',
	'Send':'Αποστολή',
	'Clear':'Εκκαθάριση',
	'<span class="req">*</span> Required fields':'<span class="req">*</span> Απαραίτητα πεδία',
    '<a href="http://c00kiemon5ter.github.com/about">c00kiemon5ter</a> loves cookies and ice cream. He\'s into coding, system architecture and open source software. Besides information technology, he likes <a href="http://bit.ly/c00kiemusic">music</a>, riding his bike and studying philosophy.':'Ο <a href="http://c00kiemon5ter.github.com/about">c00kiemon5ter</a> λατρέυει τα μπισκότα και το παγωτό. Ασχολείται με το προγραμματισμό, την αρχιτεκτονική συστημάτων και το ανοιχτό λογισμικό. Εκτός απ την τεχνολογία αγαπάει τη μουσική, το ποδήλατο και τη φιλοσοφία.',
    '<a href="http://uberspot.github.com/#about">uberspot</a> is an undergraduate student of <a href="http://www.aueb.gr">Athen University of Economics and Business</a> <a href="http://www.cs.aueb.gr">Computer Science Department</a> that doesn\'t really like talking about himself.':'Ο <a href="http://uberspot.github.com/#about">uberspot</a> είναι τελειόφοιτος φοιτητής του <a href="http://www.aueb.gr">Οικονομικού Πανεπιστημίου Αθηνών</a> στο <a href="http://www.cs.aueb.gr">Τμήμα Πληροφορικής</a> και δε του αρέσει να γράφει για τον εαυτό του.',
    '<a href="http://masterex.github.com/about.html">master_ex</a> is an undergraduate student of <a href="http://www.aueb.gr">Athen University of Economics and Business</a> <a href="http://www.cs.aueb.gr">Computer Science Department</a>. He likes web development, web design, system administration and SEO':'Ο <a href="http://masterex.github.com/about.html">master_ex</a> είναι τελειόφοιτος φοιτητής του <a href="http://www.aueb.gr">Οικονομικού Πανεπιστημίου Αθηνών</a> στο <a href="http://www.cs.aueb.gr">Τμήμα Πληροφορικής</a>. Ασχολείται με web development, web design, system administration και SEO',
}
