jquery_lang_js.prototype.lang.el = {
	'Home':'Αρχική',
	'About':'Σχετικα',
	'Portofolio':'Πορτοφολιο',
	'Prices':'Τιμες',
	'Contact':'Επικοινωνια',
	'About WebWizards':'Σχετικα Με Τους WebWizards',
	'Webwizards are a small and agile group of computer science students, that specialize in web development and in applying new and innovative technologies. Our purpose is to reinforce the web profile of your company through the usage of functional and appealing web pages and other web services, resulting in a transition to the digital age. Some of the technologies we specialize in are:  <ul><li> Server Side: PHP//CakePHP, Python//Django, CGI</li> <li>Client Side: HTML5, CSS3, JavaScript, JQuery </li><li>CMS: Joomla!, Wordpress, Django-CMS <li></ul> ':'Οι WebWizards είναι μία μικρή και ευέλικτη ομάδα φοιτητών πληροφορικής, που εξειδικεύονται στη κατασκευή ιστοσελίδων και την εφαρμογή νέων και καινοτόμων τεχνολογιών. Σκοπός μας είναι να ενισχύσουμε το διαδικτυακό προφίλ της εταιρίας σας, μέσα από τη χρήση λειτουργικών και όμορφων ιστοσελίδων και άλλων διαδικτυακών υπηρεσιών, με αποτέλεσμα τον εκσυγχρονισμό της εταιρίας σας και τη μετάβασή της στη ψηφιακή εποχή.   Ανάλογα με τις ανάγκες σας θα χρησιμοποιήσουμε και τις πιο κατάλληλες τεχνολογίες. Οι WebWizards εξειδικεύονται σε πληθώρα τεχνολογιών:   <ul><li> Server Side: PHP//CakePHP, Python//Django, CGI</li> <li>Client Side: HTML5, CSS3, JavaScript, JQuery </li><li>CMS: Joomla!, Wordpress, Django-CMS <li></ul>',
	'Who Are We?':'Ποιοι Είμαστε;',
	'Portfolio':'Δουλειές Μας',
	'Pricelist':'Κοστολόγιο',
	'Prices....':'Τιμές....',
	'Contact':'Επικοινωνια',
	'Name <span class="req">*</span>':'Όνομα <span class="req">*</span>',
	'Email <span class="req">*</span>':'Email <span class="req">*</span>',
	'Message':'Μήνυμα',
	'Send':'Αποστολή',
	'Clear':'Εκκαθάριση',
	'<span class="req">*</span> Required fields':'<span class="req">*</span> Απαραίτητα πεδία',
}
